[package]
name = "state-engine"
version = "0.1.0"
authors = ["Medetashi <qebju@animagram.jp>"]
edition = "2026"
license = "MIT"
description = """
state-engine - Conductor向けマルチストアステート管理ライブラリ
"""

repository = ""

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

[features]
default = []