[package]
name = "state-engine"
version = "0.1.0"
authors = ["Medetashi <qebju@animagram.jp>"]
edition = "2024"
license = "MIT"
description = """
conduct-engine: A Declarative Data-State Engine for Rust & WebAssembly
"""

repository = ""

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
regex = "1.10"

[features]
default = []